# This file was generated by GoReleaser. DO NOT EDIT.
cask "many-ai-cli" do
  version "0.4.0"

  on_macos do
    on_intel do
      sha256 "65937f41374e7e286c05465ade7a87dd7572ffac30689b15b95f93f9aa8d712c"
      url "https://github.com/ishizakahiroshi/many-ai-cli/releases/download/v#{version}/many-ai-cli-#{version}-macos-intel.zip"
    end
    on_arm do
      sha256 "05e160155882b22c632add09b62557a9a5409f4b6d5cb4d9e6f9472de3cb0d93"
      url "https://github.com/ishizakahiroshi/many-ai-cli/releases/download/v#{version}/many-ai-cli-#{version}-macos-apple-silicon.zip"
    end
  end

  on_linux do
    on_intel do
      sha256 "ac8f621b022dd1e7c1d59357f09bbe2dcb64002336f9709432466e95a0e2759d"
      url "https://github.com/ishizakahiroshi/many-ai-cli/releases/download/v#{version}/many-ai-cli-#{version}-linux-x64.zip"
    end
  end

  name "many-ai-cli"
  desc "Web dashboard to manage approvals and progress across multiple AI coding CLIs"
  homepage "https://github.com/ishizakahiroshi/many-ai-cli"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "many-ai-cli"

  postflight do
    if system_command("/usr/bin/xattr", args: ["-h"]).exit_status == 0
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/many-ai-cli"]
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/many-ai-cli-launcher"]
    end
  end

  # No zap stanza required

end
