# This file was generated by GoReleaser. DO NOT EDIT.
cask "many-ai-cli" do
  version "0.3.3"

  on_macos do
    on_intel do
      sha256 "1fde6f14969c13f828ad23cc47f8b4593c1c58b08f81405501cdd0db0a04e955"
      url "https://github.com/ishizakahiroshi/many-ai-cli/releases/download/v#{version}/many-ai-cli-#{version}-macos-intel.zip"
    end
    on_arm do
      sha256 "320a8161b33734395041b8f77845769690faa54e7a3089e2376fb25e4ae9cd52"
      url "https://github.com/ishizakahiroshi/many-ai-cli/releases/download/v#{version}/many-ai-cli-#{version}-macos-apple-silicon.zip"
    end
  end

  on_linux do
    on_intel do
      sha256 "5e861c9f57ba7eb2bed8435e874be6f81ca8ae27b9d794e0d7d70233355194fc"
      url "https://github.com/ishizakahiroshi/many-ai-cli/releases/download/v#{version}/many-ai-cli-#{version}-linux-x64.zip"
    end
  end

  name "many-ai-cli"
  desc "Web dashboard to manage approvals and progress across multiple AI coding CLIs"
  homepage "https://github.com/ishizakahiroshi/many-ai-cli"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "many-ai-cli"

  postflight do
    if system_command("/usr/bin/xattr", args: ["-h"]).exit_status == 0
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/many-ai-cli"]
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/many-ai-cli-launcher"]
    end
  end

  # No zap stanza required

end
