# This file was generated by GoReleaser. DO NOT EDIT.
cask "many-ai-cli" do
  version "0.8.0"

  on_macos do
    on_arm do
      sha256 "2eb2eada861cc94340c47e89b6b7bdfebfc49df1b7d8fbe78e307a03379d4d6f"
      url "https://github.com/ishizakahiroshi/many-ai-cli/releases/download/v#{version}/many-ai-cli-#{version}-macos-apple-silicon.zip"
    end
    on_intel do
      sha256 "456cd6df5c02edabc51c7496fc0e3ab971f3b3d3e05d409620eb6925a018d950"
      url "https://github.com/ishizakahiroshi/many-ai-cli/releases/download/v#{version}/many-ai-cli-#{version}-macos-intel.zip"
    end
  end
  on_linux do
    on_intel do
      sha256 "161ba4edab4583c123d2d5af31fe9d7a30092c18d7d1b93bab2430e0e5365d6a"
      url "https://github.com/ishizakahiroshi/many-ai-cli/releases/download/v#{version}/many-ai-cli-#{version}-linux-x64.zip"
    end
  end

  name "many-ai-cli"
  desc "Web dashboard to manage approvals and progress across multiple AI coding CLIs"
  homepage "https://github.com/ishizakahiroshi/many-ai-cli"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "many-ai-cli"

  postflight do
    if system_command("/usr/bin/xattr", args: ["-h"]).exit_status == 0
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/many-ai-cli"]
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/many-ai-cli-launcher"]
    end
  end

  # No zap stanza required
end
